name: dashlog
description: Command line tool for generating a changelog from git tags and semantic commit history.
version: 0.0.2
homepage: https://github.com/herveGuigoz/dashlog

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  dashlog: main

dependencies: 
  args: ^2.1.1
  mustache_template: ^2.0.0
  process_run: ^0.12.1+1
  
dev_dependencies:
  build_runner: ^2.0.6
  build_version: ^2.0.3
  pedantic: ^1.9.0
  test: ^1.14.4

